spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dingdong?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  servlet:
    session:
      cookie:
        domain: ${CLIENT_ADDRESS}
        same-site: strict
        path: /

cache:
  cleanupIntervalMinutes: 5

client:
  schema: ${CLIENT_SCHEMA}
  ip: ${CLIENT_ADDRESS}
  port: ${CLIENT_PORT}

api:
  tmap:
    apikeys:
      - ${API_KEY_1}
      - ${API_KEY_2}
      - ${API_KEY_3}

fcm:
  renotify: ${FCM_RENOTIFIY}
  silent: ${FCM_SILENT}
  requireInteraction: ${FCM_REQUIRE_INTERACTION}
  link: ${FCM_TOUCH_LINK}
  image: ${FCM_IMAGE}
  icon: ${FCM_ICON}
  badge: ${FCM_BADGE}

  message:
    allocate:
      success:
        title: ${ALLOCATE_SUCCESS_TITLE}
        content: ${ALLOCATE_SUCCESS_CONTENT}
      fail:
        title: ${ALLOCATE_FAIL_TITLE}
        content: ${ALLOCATE_FAIL_CONTENT}
    bus:
      start:
        title: ${BUS_START_TITLE}

# prometheus endpoint expose
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  prometheus:
    metrics:
      export:
        enabled: true
